### ISSUE TITLE
feature request: append signature/footer

### ISSUE THREAD

**Issue by chri2** [oe4dns/tootgroup.py#14]
When tootgroup.py re-toots a note there is no option to put the information into it who actually wrote the original toot if it is not public by itself (and even then it might need some searching).

It would be great if it'd be possible to configure a kind of footer/signature containing a placeholder for the original account name.

**Comment by oe4dns** [comment]
The current situation is as follows:

tootgroup.py "boosts/retoots" group posts. The originator is fully visible in this case because no new message is created.

tootgroup.py creates new posts from private messages it receives. The originator is not visible but this is intentional. This is useful if more than one person acts as an organisation, a club or whatever.

My suggestion is manually including the footer if it is desired.
