### ISSUE TITLE
Possible hack for supporting !group

### ISSUE THREAD

**Issue by georgedorn** [oe4dns/tootgroup.py#2]
If users were followed by the bot (by the user sending a DM saying 'join' or something?) the bot could listen for !group instead of !@group.

That'd make it a followbot (albeit an opt-in followbot) so that should probably come with a warning not to run the bot's account on a non-bot instance.

**Comment by oe4dns** [comment]
Please elaborate - I do not fully understand what you mean but I try to answer as much as I can.

The users have to be followed by the bot. That is the core of how it is supposed to work. Followed accounts are to be curated by one or more administrator(s) and not added automagically.

There is a reason for using !@group  -  only if you mention the bot correctly, it receives a notification that will then trigger the bot's action.

!group would mean that tootgroup.py has to check every message in its timeline. That is possible but would require more ressources.

Autofollow etc. is currently not planned. tootgroup.py is meant for curated groups of people (bots, animals plants and creatues) that are somehow related to the group and/or its topic. Instead of an open autofollow group, I'd suggest just pinning a specific #hashtag in your client.
